export const plans = [
  {
    id: 1,
    title: "Basic Plan",
    price: "$0",
    subtitle: "per editor/month billed monthly",
    features: [
      "30h Fast generations",
      "Unlimited Relaxed generations",
      "General commercial terms",
      "Access to member gallery",
      "Optional credit top ups",
      "3 concurrent fast jobs",
      "12 concurrent fast jobs",
    ],
    buttonText: "Current Plan",
    buttonType: "current",
  },
  {
    id: 2,
    title: "Standard Plan",
    price: "$30",
    subtitle: "per editor/month billed monthly",
    features: [
      "15h Fast generations",
      "Unlimited Relaxed generations",
      "General commercial terms",
      "Access to member gallery",
      "Optional credit top ups",
      "3 concurrent fast jobs",
      "12 concurrent fast jobs",
    ],
    buttonText: "Choose Plan",
    buttonType: "choose",
    popular: true,
  },
  {
    id: 3,
    title: "Pro Plan",
    price: "$60",
    subtitle: "per editor/month billed monthly",
    features: [
      "30h Fast generations",
      "Unlimited Relaxed generations",
      "General commercial terms",
      "Access to member gallery",
      "Optional credit top ups",
      "3 concurrent fast jobs",
      "12 concurrent fast jobs",
    ],
    buttonText: "Choose Plan",
    buttonType: "choose",
  },
  {
    id: 4,
    title: "Unlimited Plan",
    price: "$120",
    subtitle: "per editor/month billed monthly",
    features: [
      "60h Fast generations",
      "Unlimited Relaxed generations",
      "General commercial terms",
      "Access to member gallery",
      "Optional credit top ups",
      "3 concurrent fast jobs",
      "12 concurrent fast jobs",
    ],
    buttonText: "Choose Plan",
    buttonType: "choose",
  },
];